//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mre.Externos.ServiceReferenceAsuntosMigratorios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class SolicitudInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaWsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionResidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExoneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaCaducidadDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaEmisionDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdActividadVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdActoConsularSolicitudVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdActoConsularVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCalidadMigratoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCentroAdministrativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCiudadNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCiudadResidenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEntidadAuspicianteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioCajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioCreacionEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdGrupoVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdNacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdTramiteNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LugarEmisionDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresExtranjeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroVisaNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoExtranjeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mre.Externos.ServiceReferenceAsuntosMigratorios.RequisitosSolicitudMessage[] RequisitosVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoExtranjeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioWsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs {
            get {
                return this.ContraseniaWsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaWsField, value) != true)) {
                    this.ContraseniaWsField = value;
                    this.RaisePropertyChanged("ContraseniaWs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionResidencia {
            get {
                return this.DireccionResidenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionResidenciaField, value) != true)) {
                    this.DireccionResidenciaField = value;
                    this.RaisePropertyChanged("DireccionResidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Exoneracion {
            get {
                return this.ExoneracionField;
            }
            set {
                if ((this.ExoneracionField.Equals(value) != true)) {
                    this.ExoneracionField = value;
                    this.RaisePropertyChanged("Exoneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCaducidadDocumento {
            get {
                return this.FechaCaducidadDocumentoField;
            }
            set {
                if ((this.FechaCaducidadDocumentoField.Equals(value) != true)) {
                    this.FechaCaducidadDocumentoField = value;
                    this.RaisePropertyChanged("FechaCaducidadDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEmisionDocumento {
            get {
                return this.FechaEmisionDocumentoField;
            }
            set {
                if ((this.FechaEmisionDocumentoField.Equals(value) != true)) {
                    this.FechaEmisionDocumentoField = value;
                    this.RaisePropertyChanged("FechaEmisionDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistroSolicitud {
            get {
                return this.FechaRegistroSolicitudField;
            }
            set {
                if ((this.FechaRegistroSolicitudField.Equals(value) != true)) {
                    this.FechaRegistroSolicitudField = value;
                    this.RaisePropertyChanged("FechaRegistroSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActividadVisa {
            get {
                return this.IdActividadVisaField;
            }
            set {
                if ((this.IdActividadVisaField.Equals(value) != true)) {
                    this.IdActividadVisaField = value;
                    this.RaisePropertyChanged("IdActividadVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularSolicitudVisa {
            get {
                return this.IdActoConsularSolicitudVisaField;
            }
            set {
                if ((this.IdActoConsularSolicitudVisaField.Equals(value) != true)) {
                    this.IdActoConsularSolicitudVisaField = value;
                    this.RaisePropertyChanged("IdActoConsularSolicitudVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularVisa {
            get {
                return this.IdActoConsularVisaField;
            }
            set {
                if ((this.IdActoConsularVisaField.Equals(value) != true)) {
                    this.IdActoConsularVisaField = value;
                    this.RaisePropertyChanged("IdActoConsularVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCalidadMigratoria {
            get {
                return this.IdCalidadMigratoriaField;
            }
            set {
                if ((this.IdCalidadMigratoriaField.Equals(value) != true)) {
                    this.IdCalidadMigratoriaField = value;
                    this.RaisePropertyChanged("IdCalidadMigratoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAdministrativo {
            get {
                return this.IdCentroAdministrativoField;
            }
            set {
                if ((this.IdCentroAdministrativoField.Equals(value) != true)) {
                    this.IdCentroAdministrativoField = value;
                    this.RaisePropertyChanged("IdCentroAdministrativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCiudadNacimiento {
            get {
                return this.IdCiudadNacimientoField;
            }
            set {
                if ((this.IdCiudadNacimientoField.Equals(value) != true)) {
                    this.IdCiudadNacimientoField = value;
                    this.RaisePropertyChanged("IdCiudadNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCiudadResidencia {
            get {
                return this.IdCiudadResidenciaField;
            }
            set {
                if ((this.IdCiudadResidenciaField.Equals(value) != true)) {
                    this.IdCiudadResidenciaField = value;
                    this.RaisePropertyChanged("IdCiudadResidencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEntidadAuspiciante {
            get {
                return this.IdEntidadAuspicianteField;
            }
            set {
                if ((this.IdEntidadAuspicianteField.Equals(value) != true)) {
                    this.IdEntidadAuspicianteField = value;
                    this.RaisePropertyChanged("IdEntidadAuspiciante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaPago {
            get {
                return this.IdFormaPagoField;
            }
            set {
                if ((this.IdFormaPagoField.Equals(value) != true)) {
                    this.IdFormaPagoField = value;
                    this.RaisePropertyChanged("IdFormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCajero {
            get {
                return this.IdFuncionarioCajeroField;
            }
            set {
                if ((this.IdFuncionarioCajeroField.Equals(value) != true)) {
                    this.IdFuncionarioCajeroField = value;
                    this.RaisePropertyChanged("IdFuncionarioCajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCreacionEsigex {
            get {
                return this.IdFuncionarioCreacionEsigexField;
            }
            set {
                if ((this.IdFuncionarioCreacionEsigexField.Equals(value) != true)) {
                    this.IdFuncionarioCreacionEsigexField = value;
                    this.RaisePropertyChanged("IdFuncionarioCreacionEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema {
            get {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set {
                if ((this.IdFuncionarioNuevoSistemaField.Equals(value) != true)) {
                    this.IdFuncionarioNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdFuncionarioNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGrupoVisa {
            get {
                return this.IdGrupoVisaField;
            }
            set {
                if ((this.IdGrupoVisaField.Equals(value) != true)) {
                    this.IdGrupoVisaField = value;
                    this.RaisePropertyChanged("IdGrupoVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdNacionalidad {
            get {
                return this.IdNacionalidadField;
            }
            set {
                if ((this.IdNacionalidadField.Equals(value) != true)) {
                    this.IdNacionalidadField = value;
                    this.RaisePropertyChanged("IdNacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipoDocumento {
            get {
                return this.IdTipoDocumentoField;
            }
            set {
                if ((this.IdTipoDocumentoField.Equals(value) != true)) {
                    this.IdTipoDocumentoField = value;
                    this.RaisePropertyChanged("IdTipoDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema {
            get {
                return this.IdTramiteNuevoSistemaField;
            }
            set {
                if ((this.IdTramiteNuevoSistemaField.Equals(value) != true)) {
                    this.IdTramiteNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdTramiteNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LugarEmisionDocumento {
            get {
                return this.LugarEmisionDocumentoField;
            }
            set {
                if ((this.LugarEmisionDocumentoField.Equals(value) != true)) {
                    this.LugarEmisionDocumentoField = value;
                    this.RaisePropertyChanged("LugarEmisionDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombresExtranjero {
            get {
                return this.NombresExtranjeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresExtranjeroField, value) != true)) {
                    this.NombresExtranjeroField = value;
                    this.RaisePropertyChanged("NombresExtranjero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobante {
            get {
                return this.NumeroComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroComprobanteField, value) != true)) {
                    this.NumeroComprobanteField = value;
                    this.RaisePropertyChanged("NumeroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDocumento {
            get {
                return this.NumeroDocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroDocumentoField, value) != true)) {
                    this.NumeroDocumentoField = value;
                    this.RaisePropertyChanged("NumeroDocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroFacturaField, value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisaNuevoSistema {
            get {
                return this.NumeroVisaNuevoSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroVisaNuevoSistemaField, value) != true)) {
                    this.NumeroVisaNuevoSistemaField = value;
                    this.RaisePropertyChanged("NumeroVisaNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionSolicitud {
            get {
                return this.ObservacionSolicitudField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionSolicitudField, value) != true)) {
                    this.ObservacionSolicitudField = value;
                    this.RaisePropertyChanged("ObservacionSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellidoExtranjero {
            get {
                return this.PrimerApellidoExtranjeroField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoExtranjeroField, value) != true)) {
                    this.PrimerApellidoExtranjeroField = value;
                    this.RaisePropertyChanged("PrimerApellidoExtranjero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mre.Externos.ServiceReferenceAsuntosMigratorios.RequisitosSolicitudMessage[] RequisitosVisa {
            get {
                return this.RequisitosVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.RequisitosVisaField, value) != true)) {
                    this.RequisitosVisaField = value;
                    this.RaisePropertyChanged("RequisitosVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellidoExtranjero {
            get {
                return this.SegundoApellidoExtranjeroField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoExtranjeroField, value) != true)) {
                    this.SegundoApellidoExtranjeroField = value;
                    this.RaisePropertyChanged("SegundoApellidoExtranjero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs {
            get {
                return this.UsuarioWsField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioWsField, value) != true)) {
                    this.UsuarioWsField = value;
                    this.RaisePropertyChanged("UsuarioWs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequisitosSolicitudMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class RequisitosSolicitudMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdActoConsularVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdRequisitoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SeleccionadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularVisa {
            get {
                return this.IdActoConsularVisaField;
            }
            set {
                if ((this.IdActoConsularVisaField.Equals(value) != true)) {
                    this.IdActoConsularVisaField = value;
                    this.RaisePropertyChanged("IdActoConsularVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdRequisito {
            get {
                return this.IdRequisitoField;
            }
            set {
                if ((this.IdRequisitoField.Equals(value) != true)) {
                    this.IdRequisitoField = value;
                    this.RaisePropertyChanged("IdRequisito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacion {
            get {
                return this.ObservacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionField, value) != true)) {
                    this.ObservacionField = value;
                    this.RaisePropertyChanged("Observacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Seleccionado {
            get {
                return this.SeleccionadoField;
            }
            set {
                if ((this.SeleccionadoField.Equals(value) != true)) {
                    this.SeleccionadoField = value;
                    this.RaisePropertyChanged("Seleccionado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resultado", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionVisaMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionSolicitudMessage))]
    public partial class Resultado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoDescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoDescripcion {
            get {
                return this.CodigoDescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoDescripcionField, value) != true)) {
                    this.CodigoDescripcionField = value;
                    this.RaisePropertyChanged("CodigoDescripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneracionVisaMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class GeneracionVisaMessage : Mre.Externos.ServiceReferenceAsuntosMigratorios.Resultado {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteVisa {
            get {
                return this.IdTramiteVisaField;
            }
            set {
                if ((this.IdTramiteVisaField.Equals(value) != true)) {
                    this.IdTramiteVisaField = value;
                    this.RaisePropertyChanged("IdTramiteVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTramite {
            get {
                return this.NumeroTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTramiteField, value) != true)) {
                    this.NumeroTramiteField = value;
                    this.RaisePropertyChanged("NumeroTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCedulacionMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class OrdenCedulacionMessage : Mre.Externos.ServiceReferenceAsuntosMigratorios.Resultado {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoVerificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SecuencialActuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoVerificacion {
            get {
                return this.CodigoVerificacionField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoVerificacionField, value) != true)) {
                    this.CodigoVerificacionField = value;
                    this.RaisePropertyChanged("CodigoVerificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteOrdenCedulacion {
            get {
                return this.IdTramiteOrdenCedulacionField;
            }
            set {
                if ((this.IdTramiteOrdenCedulacionField.Equals(value) != true)) {
                    this.IdTramiteOrdenCedulacionField = value;
                    this.RaisePropertyChanged("IdTramiteOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTramite {
            get {
                return this.NumeroTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTramiteField, value) != true)) {
                    this.NumeroTramiteField = value;
                    this.RaisePropertyChanged("NumeroTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SecuencialActuacion {
            get {
                return this.SecuencialActuacionField;
            }
            set {
                if ((this.SecuencialActuacionField.Equals(value) != true)) {
                    this.SecuencialActuacionField = value;
                    this.RaisePropertyChanged("SecuencialActuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneracionSolicitudMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class GeneracionSolicitudMessage : Mre.Externos.ServiceReferenceAsuntosMigratorios.Resultado {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSecuencialActuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroVisaEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSecuencialActuacion {
            get {
                return this.IdSecuencialActuacionField;
            }
            set {
                if ((this.IdSecuencialActuacionField.Equals(value) != true)) {
                    this.IdSecuencialActuacionField = value;
                    this.RaisePropertyChanged("IdSecuencialActuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteSolicitud {
            get {
                return this.IdTramiteSolicitudField;
            }
            set {
                if ((this.IdTramiteSolicitudField.Equals(value) != true)) {
                    this.IdTramiteSolicitudField = value;
                    this.RaisePropertyChanged("IdTramiteSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTramite {
            get {
                return this.NumeroTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTramiteField, value) != true)) {
                    this.NumeroTramiteField = value;
                    this.RaisePropertyChanged("NumeroTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisaEsigex {
            get {
                return this.NumeroVisaEsigexField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroVisaEsigexField, value) != true)) {
                    this.NumeroVisaEsigexField = value;
                    this.RaisePropertyChanged("NumeroVisaEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VisaInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class VisaInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaWsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentoPdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExoneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaVigenciaVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioCajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioEsigexAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioEsigexVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdTramiteNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroEntradasPermitidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroVisaNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionAutorizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioWsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VisaAutorizadaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs {
            get {
                return this.ContraseniaWsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaWsField, value) != true)) {
                    this.ContraseniaWsField = value;
                    this.RaisePropertyChanged("ContraseniaWs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentoPdf {
            get {
                return this.DocumentoPdfField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoPdfField, value) != true)) {
                    this.DocumentoPdfField = value;
                    this.RaisePropertyChanged("DocumentoPdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Exoneracion {
            get {
                return this.ExoneracionField;
            }
            set {
                if ((this.ExoneracionField.Equals(value) != true)) {
                    this.ExoneracionField = value;
                    this.RaisePropertyChanged("Exoneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaAutorizacion {
            get {
                return this.FechaAutorizacionField;
            }
            set {
                if ((this.FechaAutorizacionField.Equals(value) != true)) {
                    this.FechaAutorizacionField = value;
                    this.RaisePropertyChanged("FechaAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaVigenciaVisa {
            get {
                return this.FechaVigenciaVisaField;
            }
            set {
                if ((this.FechaVigenciaVisaField.Equals(value) != true)) {
                    this.FechaVigenciaVisaField = value;
                    this.RaisePropertyChanged("FechaVigenciaVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaPago {
            get {
                return this.IdFormaPagoField;
            }
            set {
                if ((this.IdFormaPagoField.Equals(value) != true)) {
                    this.IdFormaPagoField = value;
                    this.RaisePropertyChanged("IdFormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCajero {
            get {
                return this.IdFuncionarioCajeroField;
            }
            set {
                if ((this.IdFuncionarioCajeroField.Equals(value) != true)) {
                    this.IdFuncionarioCajeroField = value;
                    this.RaisePropertyChanged("IdFuncionarioCajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioEsigexAutorizacion {
            get {
                return this.IdFuncionarioEsigexAutorizacionField;
            }
            set {
                if ((this.IdFuncionarioEsigexAutorizacionField.Equals(value) != true)) {
                    this.IdFuncionarioEsigexAutorizacionField = value;
                    this.RaisePropertyChanged("IdFuncionarioEsigexAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioEsigexVisa {
            get {
                return this.IdFuncionarioEsigexVisaField;
            }
            set {
                if ((this.IdFuncionarioEsigexVisaField.Equals(value) != true)) {
                    this.IdFuncionarioEsigexVisaField = value;
                    this.RaisePropertyChanged("IdFuncionarioEsigexVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema {
            get {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set {
                if ((this.IdFuncionarioNuevoSistemaField.Equals(value) != true)) {
                    this.IdFuncionarioNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdFuncionarioNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema {
            get {
                return this.IdTramiteNuevoSistemaField;
            }
            set {
                if ((this.IdTramiteNuevoSistemaField.Equals(value) != true)) {
                    this.IdTramiteNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdTramiteNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteSolicitud {
            get {
                return this.IdTramiteSolicitudField;
            }
            set {
                if ((this.IdTramiteSolicitudField.Equals(value) != true)) {
                    this.IdTramiteSolicitudField = value;
                    this.RaisePropertyChanged("IdTramiteSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobante {
            get {
                return this.NumeroComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroComprobanteField, value) != true)) {
                    this.NumeroComprobanteField = value;
                    this.RaisePropertyChanged("NumeroComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroEntradasPermitidas {
            get {
                return this.NumeroEntradasPermitidasField;
            }
            set {
                if ((this.NumeroEntradasPermitidasField.Equals(value) != true)) {
                    this.NumeroEntradasPermitidasField = value;
                    this.RaisePropertyChanged("NumeroEntradasPermitidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroFacturaField, value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisaNuevoSistema {
            get {
                return this.NumeroVisaNuevoSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroVisaNuevoSistemaField, value) != true)) {
                    this.NumeroVisaNuevoSistemaField = value;
                    this.RaisePropertyChanged("NumeroVisaNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionAutorizacion {
            get {
                return this.ObservacionAutorizacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionAutorizacionField, value) != true)) {
                    this.ObservacionAutorizacionField = value;
                    this.RaisePropertyChanged("ObservacionAutorizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs {
            get {
                return this.UsuarioWsField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioWsField, value) != true)) {
                    this.UsuarioWsField = value;
                    this.RaisePropertyChanged("UsuarioWs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VisaAutorizada {
            get {
                return this.VisaAutorizadaField;
            }
            set {
                if ((this.VisaAutorizadaField.Equals(value) != true)) {
                    this.VisaAutorizadaField = value;
                    this.RaisePropertyChanged("VisaAutorizada");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCedulacionInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class OrdenCedulacionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaWsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiasValidezField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinValidezOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioValidezOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdActoConsularOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCentroAdministrativoOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdExoneracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFormaPagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioCajeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioCreacionEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioPagoEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioSignatarioEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdTramiteNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteVisaEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroComprobantePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroFacturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioWsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs {
            get {
                return this.ContraseniaWsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaWsField, value) != true)) {
                    this.ContraseniaWsField = value;
                    this.RaisePropertyChanged("ContraseniaWs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiasValidez {
            get {
                return this.DiasValidezField;
            }
            set {
                if ((this.DiasValidezField.Equals(value) != true)) {
                    this.DiasValidezField = value;
                    this.RaisePropertyChanged("DiasValidez");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura {
            get {
                return this.FechaFacturaField;
            }
            set {
                if ((this.FechaFacturaField.Equals(value) != true)) {
                    this.FechaFacturaField = value;
                    this.RaisePropertyChanged("FechaFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFinValidezOrdenCedulacion {
            get {
                return this.FechaFinValidezOrdenCedulacionField;
            }
            set {
                if ((this.FechaFinValidezOrdenCedulacionField.Equals(value) != true)) {
                    this.FechaFinValidezOrdenCedulacionField = value;
                    this.RaisePropertyChanged("FechaFinValidezOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicioValidezOrdenCedulacion {
            get {
                return this.FechaInicioValidezOrdenCedulacionField;
            }
            set {
                if ((this.FechaInicioValidezOrdenCedulacionField.Equals(value) != true)) {
                    this.FechaInicioValidezOrdenCedulacionField = value;
                    this.RaisePropertyChanged("FechaInicioValidezOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago {
            get {
                return this.FechaPagoField;
            }
            set {
                if ((this.FechaPagoField.Equals(value) != true)) {
                    this.FechaPagoField = value;
                    this.RaisePropertyChanged("FechaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistroOrdenCedulacion {
            get {
                return this.FechaRegistroOrdenCedulacionField;
            }
            set {
                if ((this.FechaRegistroOrdenCedulacionField.Equals(value) != true)) {
                    this.FechaRegistroOrdenCedulacionField = value;
                    this.RaisePropertyChanged("FechaRegistroOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularOrdenCedulacion {
            get {
                return this.IdActoConsularOrdenCedulacionField;
            }
            set {
                if ((this.IdActoConsularOrdenCedulacionField.Equals(value) != true)) {
                    this.IdActoConsularOrdenCedulacionField = value;
                    this.RaisePropertyChanged("IdActoConsularOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAdministrativoOrdenCedulacion {
            get {
                return this.IdCentroAdministrativoOrdenCedulacionField;
            }
            set {
                if ((this.IdCentroAdministrativoOrdenCedulacionField.Equals(value) != true)) {
                    this.IdCentroAdministrativoOrdenCedulacionField = value;
                    this.RaisePropertyChanged("IdCentroAdministrativoOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdExoneracion {
            get {
                return this.IdExoneracionField;
            }
            set {
                if ((this.IdExoneracionField.Equals(value) != true)) {
                    this.IdExoneracionField = value;
                    this.RaisePropertyChanged("IdExoneracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFormaPago {
            get {
                return this.IdFormaPagoField;
            }
            set {
                if ((this.IdFormaPagoField.Equals(value) != true)) {
                    this.IdFormaPagoField = value;
                    this.RaisePropertyChanged("IdFormaPago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCajero {
            get {
                return this.IdFuncionarioCajeroField;
            }
            set {
                if ((this.IdFuncionarioCajeroField.Equals(value) != true)) {
                    this.IdFuncionarioCajeroField = value;
                    this.RaisePropertyChanged("IdFuncionarioCajero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioCreacionEsigex {
            get {
                return this.IdFuncionarioCreacionEsigexField;
            }
            set {
                if ((this.IdFuncionarioCreacionEsigexField.Equals(value) != true)) {
                    this.IdFuncionarioCreacionEsigexField = value;
                    this.RaisePropertyChanged("IdFuncionarioCreacionEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema {
            get {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set {
                if ((this.IdFuncionarioNuevoSistemaField.Equals(value) != true)) {
                    this.IdFuncionarioNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdFuncionarioNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioPagoEsigex {
            get {
                return this.IdFuncionarioPagoEsigexField;
            }
            set {
                if ((this.IdFuncionarioPagoEsigexField.Equals(value) != true)) {
                    this.IdFuncionarioPagoEsigexField = value;
                    this.RaisePropertyChanged("IdFuncionarioPagoEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioSignatarioEsigex {
            get {
                return this.IdFuncionarioSignatarioEsigexField;
            }
            set {
                if ((this.IdFuncionarioSignatarioEsigexField.Equals(value) != true)) {
                    this.IdFuncionarioSignatarioEsigexField = value;
                    this.RaisePropertyChanged("IdFuncionarioSignatarioEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema {
            get {
                return this.IdTramiteNuevoSistemaField;
            }
            set {
                if ((this.IdTramiteNuevoSistemaField.Equals(value) != true)) {
                    this.IdTramiteNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdTramiteNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteVisaEsigex {
            get {
                return this.IdTramiteVisaEsigexField;
            }
            set {
                if ((this.IdTramiteVisaEsigexField.Equals(value) != true)) {
                    this.IdTramiteVisaEsigexField = value;
                    this.RaisePropertyChanged("IdTramiteVisaEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroComprobantePago {
            get {
                return this.NumeroComprobantePagoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroComprobantePagoField, value) != true)) {
                    this.NumeroComprobantePagoField = value;
                    this.RaisePropertyChanged("NumeroComprobantePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura {
            get {
                return this.NumeroFacturaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroFacturaField, value) != true)) {
                    this.NumeroFacturaField = value;
                    this.RaisePropertyChanged("NumeroFactura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionOrdenCedulacion {
            get {
                return this.ObservacionOrdenCedulacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionOrdenCedulacionField, value) != true)) {
                    this.ObservacionOrdenCedulacionField = value;
                    this.RaisePropertyChanged("ObservacionOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs {
            get {
                return this.UsuarioWsField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioWsField, value) != true)) {
                    this.UsuarioWsField = value;
                    this.RaisePropertyChanged("UsuarioWs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdenCedulacionV2Info", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class OrdenCedulacionV2Info : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaWsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DocumentoPdfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroOrdenCedulacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdFuncionarioNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioOrdenCedulacionEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdTramiteNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteOrdenCedulacionEsigexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioWsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContraseniaWs {
            get {
                return this.ContraseniaWsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaWsField, value) != true)) {
                    this.ContraseniaWsField = value;
                    this.RaisePropertyChanged("ContraseniaWs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] DocumentoPdf {
            get {
                return this.DocumentoPdfField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoPdfField, value) != true)) {
                    this.DocumentoPdfField = value;
                    this.RaisePropertyChanged("DocumentoPdf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistroOrdenCedulacion {
            get {
                return this.FechaRegistroOrdenCedulacionField;
            }
            set {
                if ((this.FechaRegistroOrdenCedulacionField.Equals(value) != true)) {
                    this.FechaRegistroOrdenCedulacionField = value;
                    this.RaisePropertyChanged("FechaRegistroOrdenCedulacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdFuncionarioNuevoSistema {
            get {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set {
                if ((this.IdFuncionarioNuevoSistemaField.Equals(value) != true)) {
                    this.IdFuncionarioNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdFuncionarioNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioOrdenCedulacionEsigex {
            get {
                return this.IdFuncionarioOrdenCedulacionEsigexField;
            }
            set {
                if ((this.IdFuncionarioOrdenCedulacionEsigexField.Equals(value) != true)) {
                    this.IdFuncionarioOrdenCedulacionEsigexField = value;
                    this.RaisePropertyChanged("IdFuncionarioOrdenCedulacionEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid IdTramiteNuevoSistema {
            get {
                return this.IdTramiteNuevoSistemaField;
            }
            set {
                if ((this.IdTramiteNuevoSistemaField.Equals(value) != true)) {
                    this.IdTramiteNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdTramiteNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteOrdenCedulacionEsigex {
            get {
                return this.IdTramiteOrdenCedulacionEsigexField;
            }
            set {
                if ((this.IdTramiteOrdenCedulacionEsigexField.Equals(value) != true)) {
                    this.IdTramiteOrdenCedulacionEsigexField = value;
                    this.RaisePropertyChanged("IdTramiteOrdenCedulacionEsigex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioWs {
            get {
                return this.UsuarioWsField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioWsField, value) != true)) {
                    this.UsuarioWsField = value;
                    this.RaisePropertyChanged("UsuarioWs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAsuntosMigratorios.IServiceAsuntosMigratorios")]
    public interface IServiceAsuntosMigratorios {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GuardarSolicitudVisa", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GuardarSolicitudVisaResponse")]
        Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionSolicitudMessage GuardarSolicitudVisa(Mre.Externos.ServiceReferenceAsuntosMigratorios.SolicitudInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GuardarSolicitudVisa", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GuardarSolicitudVisaResponse")]
        System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionSolicitudMessage> GuardarSolicitudVisaAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.SolicitudInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GuardarVisa", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GuardarVisaResponse")]
        Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionVisaMessage GuardarVisa(Mre.Externos.ServiceReferenceAsuntosMigratorios.VisaInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GuardarVisa", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GuardarVisaResponse")]
        System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionVisaMessage> GuardarVisaAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.VisaInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GenerarOrdenCedulacion", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GenerarOrdenCedulacionResponse")]
        Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage GenerarOrdenCedulacion(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/GenerarOrdenCedulacion", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/GenerarOrdenCedulacionResponse")]
        System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage> GenerarOrdenCedulacionAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionInfo datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/ActualizarOrdenCedulacion", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/ActualizarOrdenCedulacionResponse")]
        Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage ActualizarOrdenCedulacion(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionV2Info datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceAsuntosMigratorios/ActualizarOrdenCedulacion", ReplyAction="http://tempuri.org/IServiceAsuntosMigratorios/ActualizarOrdenCedulacionResponse")]
        System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage> ActualizarOrdenCedulacionAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionV2Info datos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceAsuntosMigratoriosChannel : Mre.Externos.ServiceReferenceAsuntosMigratorios.IServiceAsuntosMigratorios, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceAsuntosMigratoriosClient : System.ServiceModel.ClientBase<Mre.Externos.ServiceReferenceAsuntosMigratorios.IServiceAsuntosMigratorios>, Mre.Externos.ServiceReferenceAsuntosMigratorios.IServiceAsuntosMigratorios {
        
        public ServiceAsuntosMigratoriosClient() {
        }
        
        public ServiceAsuntosMigratoriosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceAsuntosMigratoriosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAsuntosMigratoriosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceAsuntosMigratoriosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionSolicitudMessage GuardarSolicitudVisa(Mre.Externos.ServiceReferenceAsuntosMigratorios.SolicitudInfo datos) {
            return base.Channel.GuardarSolicitudVisa(datos);
        }
        
        public System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionSolicitudMessage> GuardarSolicitudVisaAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.SolicitudInfo datos) {
            return base.Channel.GuardarSolicitudVisaAsync(datos);
        }
        
        public Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionVisaMessage GuardarVisa(Mre.Externos.ServiceReferenceAsuntosMigratorios.VisaInfo datos) {
            return base.Channel.GuardarVisa(datos);
        }
        
        public System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.GeneracionVisaMessage> GuardarVisaAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.VisaInfo datos) {
            return base.Channel.GuardarVisaAsync(datos);
        }
        
        public Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage GenerarOrdenCedulacion(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionInfo datos) {
            return base.Channel.GenerarOrdenCedulacion(datos);
        }
        
        public System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage> GenerarOrdenCedulacionAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionInfo datos) {
            return base.Channel.GenerarOrdenCedulacionAsync(datos);
        }
        
        public Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage ActualizarOrdenCedulacion(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionV2Info datos) {
            return base.Channel.ActualizarOrdenCedulacion(datos);
        }
        
        public System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionMessage> ActualizarOrdenCedulacionAsync(Mre.Externos.ServiceReferenceAsuntosMigratorios.OrdenCedulacionV2Info datos) {
            return base.Channel.ActualizarOrdenCedulacionAsync(datos);
        }
    }
}
