//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mre.Externos.ServiceReferenceEsigex {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleDatosVisaInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class DetalleDatosVisaInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Mre.Externos.ServiceReferenceEsigex.DatosVisaInfo[] ListDatosVisaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Mre.Externos.ServiceReferenceEsigex.DatosVisaInfo[] ListDatosVisa {
            get {
                return this.ListDatosVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListDatosVisaField, value) != true)) {
                    this.ListDatosVisaField = value;
                    this.RaisePropertyChanged("ListDatosVisa");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatosVisaInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class DatosVisaInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCaducidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaConcesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdActoConsularVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdCentroAdministrativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreActoConsularVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCentroAdministrativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPasaporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimerApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SegundoApellidoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoVisa {
            get {
                return this.EstadoVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoVisaField, value) != true)) {
                    this.EstadoVisaField = value;
                    this.RaisePropertyChanged("EstadoVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCaducidad {
            get {
                return this.FechaCaducidadField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCaducidadField, value) != true)) {
                    this.FechaCaducidadField = value;
                    this.RaisePropertyChanged("FechaCaducidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaConcesion {
            get {
                return this.FechaConcesionField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaConcesionField, value) != true)) {
                    this.FechaConcesionField = value;
                    this.RaisePropertyChanged("FechaConcesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdActoConsularVisa {
            get {
                return this.IdActoConsularVisaField;
            }
            set {
                if ((this.IdActoConsularVisaField.Equals(value) != true)) {
                    this.IdActoConsularVisaField = value;
                    this.RaisePropertyChanged("IdActoConsularVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCentroAdministrativo {
            get {
                return this.IdCentroAdministrativoField;
            }
            set {
                if ((this.IdCentroAdministrativoField.Equals(value) != true)) {
                    this.IdCentroAdministrativoField = value;
                    this.RaisePropertyChanged("IdCentroAdministrativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdTramite {
            get {
                return this.IdTramiteField;
            }
            set {
                if ((this.IdTramiteField.Equals(value) != true)) {
                    this.IdTramiteField = value;
                    this.RaisePropertyChanged("IdTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreActoConsularVisa {
            get {
                return this.NombreActoConsularVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreActoConsularVisaField, value) != true)) {
                    this.NombreActoConsularVisaField = value;
                    this.RaisePropertyChanged("NombreActoConsularVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCentroAdministrativo {
            get {
                return this.NombreCentroAdministrativoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCentroAdministrativoField, value) != true)) {
                    this.NombreCentroAdministrativoField = value;
                    this.RaisePropertyChanged("NombreCentroAdministrativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPasaporte {
            get {
                return this.NumeroPasaporteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPasaporteField, value) != true)) {
                    this.NumeroPasaporteField = value;
                    this.RaisePropertyChanged("NumeroPasaporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisa {
            get {
                return this.NumeroVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroVisaField, value) != true)) {
                    this.NumeroVisaField = value;
                    this.RaisePropertyChanged("NumeroVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido {
            get {
                return this.PrimerApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimerApellidoField, value) != true)) {
                    this.PrimerApellidoField = value;
                    this.RaisePropertyChanged("PrimerApellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido {
            get {
                return this.SegundoApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.SegundoApellidoField, value) != true)) {
                    this.SegundoApellidoField = value;
                    this.RaisePropertyChanged("SegundoApellido");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelacionVisasMessage", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class CancelacionVisasMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdActoConsularCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdActoConsularVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCentroAdministrativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCentroAdministrativoCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdFuncionarioNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSignatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteNuevoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPasaporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroVisaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesCancelacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularCancelacion {
            get {
                return this.IdActoConsularCancelacionField;
            }
            set {
                if ((this.IdActoConsularCancelacionField.Equals(value) != true)) {
                    this.IdActoConsularCancelacionField = value;
                    this.RaisePropertyChanged("IdActoConsularCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdActoConsularVisa {
            get {
                return this.IdActoConsularVisaField;
            }
            set {
                if ((this.IdActoConsularVisaField.Equals(value) != true)) {
                    this.IdActoConsularVisaField = value;
                    this.RaisePropertyChanged("IdActoConsularVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAdministrativo {
            get {
                return this.IdCentroAdministrativoField;
            }
            set {
                if ((this.IdCentroAdministrativoField.Equals(value) != true)) {
                    this.IdCentroAdministrativoField = value;
                    this.RaisePropertyChanged("IdCentroAdministrativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCentroAdministrativoCancelacion {
            get {
                return this.IdCentroAdministrativoCancelacionField;
            }
            set {
                if ((this.IdCentroAdministrativoCancelacionField.Equals(value) != true)) {
                    this.IdCentroAdministrativoCancelacionField = value;
                    this.RaisePropertyChanged("IdCentroAdministrativoCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionario {
            get {
                return this.IdFuncionarioField;
            }
            set {
                if ((this.IdFuncionarioField.Equals(value) != true)) {
                    this.IdFuncionarioField = value;
                    this.RaisePropertyChanged("IdFuncionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFuncionarioNuevoSistema {
            get {
                return this.IdFuncionarioNuevoSistemaField;
            }
            set {
                if ((this.IdFuncionarioNuevoSistemaField.Equals(value) != true)) {
                    this.IdFuncionarioNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdFuncionarioNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSignatario {
            get {
                return this.IdSignatarioField;
            }
            set {
                if ((this.IdSignatarioField.Equals(value) != true)) {
                    this.IdSignatarioField = value;
                    this.RaisePropertyChanged("IdSignatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramite {
            get {
                return this.IdTramiteField;
            }
            set {
                if ((this.IdTramiteField.Equals(value) != true)) {
                    this.IdTramiteField = value;
                    this.RaisePropertyChanged("IdTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramiteNuevoSistema {
            get {
                return this.IdTramiteNuevoSistemaField;
            }
            set {
                if ((this.IdTramiteNuevoSistemaField.Equals(value) != true)) {
                    this.IdTramiteNuevoSistemaField = value;
                    this.RaisePropertyChanged("IdTramiteNuevoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPasaporte {
            get {
                return this.NumeroPasaporteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPasaporteField, value) != true)) {
                    this.NumeroPasaporteField = value;
                    this.RaisePropertyChanged("NumeroPasaporte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroVisa {
            get {
                return this.NumeroVisaField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroVisaField, value) != true)) {
                    this.NumeroVisaField = value;
                    this.RaisePropertyChanged("NumeroVisa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObservacionesCancelacion {
            get {
                return this.ObservacionesCancelacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesCancelacionField, value) != true)) {
                    this.ObservacionesCancelacionField = value;
                    this.RaisePropertyChanged("ObservacionesCancelacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseniaField, value) != true)) {
                    this.contraseniaField = value;
                    this.RaisePropertyChanged("contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleVisaCancelacionInfo", Namespace="http://schemas.datacontract.org/2004/07/MREMH.ServiciosEsigexVisasRegularizacion." +
        "Entidad")]
    [System.SerializableAttribute()]
    public partial class DetalleVisaCancelacionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroTramiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Detalle {
            get {
                return this.DetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleField, value) != true)) {
                    this.DetalleField = value;
                    this.RaisePropertyChanged("Detalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTramite {
            get {
                return this.IdTramiteField;
            }
            set {
                if ((this.IdTramiteField.Equals(value) != true)) {
                    this.IdTramiteField = value;
                    this.RaisePropertyChanged("IdTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTramite {
            get {
                return this.NumeroTramiteField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroTramiteField, value) != true)) {
                    this.NumeroTramiteField = value;
                    this.RaisePropertyChanged("NumeroTramite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEsigex.IServiceEsigex")]
    public interface IServiceEsigex {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEsigex/BuscarVisaPorNumero", ReplyAction="http://tempuri.org/IServiceEsigex/BuscarVisaPorNumeroResponse")]
        Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo BuscarVisaPorNumero(string numeroVisa, string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEsigex/BuscarVisaPorNumero", ReplyAction="http://tempuri.org/IServiceEsigex/BuscarVisaPorNumeroResponse")]
        System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo> BuscarVisaPorNumeroAsync(string numeroVisa, string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEsigex/BuscarVisaPorDatosPersona", ReplyAction="http://tempuri.org/IServiceEsigex/BuscarVisaPorDatosPersonaResponse")]
        Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo BuscarVisaPorDatosPersona(string nombres, string primerApellido, string segundoApellido, int idNacionalidad, System.DateTime fechaNacimiento, string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEsigex/BuscarVisaPorDatosPersona", ReplyAction="http://tempuri.org/IServiceEsigex/BuscarVisaPorDatosPersonaResponse")]
        System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo> BuscarVisaPorDatosPersonaAsync(string nombres, string primerApellido, string segundoApellido, int idNacionalidad, System.DateTime fechaNacimiento, string usuario, string contrasenia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEsigex/GuardarCancelacionPorOficioVisas", ReplyAction="http://tempuri.org/IServiceEsigex/GuardarCancelacionPorOficioVisasResponse")]
        Mre.Externos.ServiceReferenceEsigex.DetalleVisaCancelacionInfo GuardarCancelacionPorOficioVisas(Mre.Externos.ServiceReferenceEsigex.CancelacionVisasMessage param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEsigex/GuardarCancelacionPorOficioVisas", ReplyAction="http://tempuri.org/IServiceEsigex/GuardarCancelacionPorOficioVisasResponse")]
        System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceEsigex.DetalleVisaCancelacionInfo> GuardarCancelacionPorOficioVisasAsync(Mre.Externos.ServiceReferenceEsigex.CancelacionVisasMessage param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEsigexChannel : Mre.Externos.ServiceReferenceEsigex.IServiceEsigex, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEsigexClient : System.ServiceModel.ClientBase<Mre.Externos.ServiceReferenceEsigex.IServiceEsigex>, Mre.Externos.ServiceReferenceEsigex.IServiceEsigex {
        
        public ServiceEsigexClient() {
        }
        
        public ServiceEsigexClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEsigexClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEsigexClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEsigexClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo BuscarVisaPorNumero(string numeroVisa, string usuario, string contrasenia) {
            return base.Channel.BuscarVisaPorNumero(numeroVisa, usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo> BuscarVisaPorNumeroAsync(string numeroVisa, string usuario, string contrasenia) {
            return base.Channel.BuscarVisaPorNumeroAsync(numeroVisa, usuario, contrasenia);
        }
        
        public Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo BuscarVisaPorDatosPersona(string nombres, string primerApellido, string segundoApellido, int idNacionalidad, System.DateTime fechaNacimiento, string usuario, string contrasenia) {
            return base.Channel.BuscarVisaPorDatosPersona(nombres, primerApellido, segundoApellido, idNacionalidad, fechaNacimiento, usuario, contrasenia);
        }
        
        public System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceEsigex.DetalleDatosVisaInfo> BuscarVisaPorDatosPersonaAsync(string nombres, string primerApellido, string segundoApellido, int idNacionalidad, System.DateTime fechaNacimiento, string usuario, string contrasenia) {
            return base.Channel.BuscarVisaPorDatosPersonaAsync(nombres, primerApellido, segundoApellido, idNacionalidad, fechaNacimiento, usuario, contrasenia);
        }
        
        public Mre.Externos.ServiceReferenceEsigex.DetalleVisaCancelacionInfo GuardarCancelacionPorOficioVisas(Mre.Externos.ServiceReferenceEsigex.CancelacionVisasMessage param) {
            return base.Channel.GuardarCancelacionPorOficioVisas(param);
        }
        
        public System.Threading.Tasks.Task<Mre.Externos.ServiceReferenceEsigex.DetalleVisaCancelacionInfo> GuardarCancelacionPorOficioVisasAsync(Mre.Externos.ServiceReferenceEsigex.CancelacionVisasMessage param) {
            return base.Channel.GuardarCancelacionPorOficioVisasAsync(param);
        }
    }
}
